import numpy as np

print("1D ARRAY:-\n")
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.power(a,b))
print(np.reciprocal(a))
print(np.reciprocal(b))

print("\n2D ARRAY:-\n")
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[2,3,4,5],[7,8,9,10]])
print(np.add(c,d))
print(np.subtract(c,d))
print(np.multiply(c,d))
print(np.divide(c,d))
print(np.mod(c,d))
print(np.power(c,d))
print(np.reciprocal(c))
print(np.reciprocal(d))